name: orbit_tracker
description: A premium, minimal habit tracker and journal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2 
  uuid: ^4.3.3 
  fl_chart: ^0.66.0
  confetti: ^0.7.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  wakelock_plus: ^1.2.8 # NEW: Keeps the screen awake!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#09090B"
  adaptive_icon_foreground: "assets/icon/icon.png"